src/Web/Microservices.Web.Frontend/Microservices.Web.Frontend/Models/DTO/Product/ProductCategory.cs
namespace Microservices.Web.Frontend.Models.DTO.Product
{
    public class ProductCategory
    {
        public string categoryId { get; set; }
        public string category { get; set; }
    }
}

src/Web/Microservices.Web.Frontend/Microservices.Web.Frontend/Models/DTO/Product/ProductDto.cs
namespace Microservices.Web.Frontend.Models.DTO.Product
{
    public class ProductDto
    {
        public string id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public object image { get; set; }
        public int price { get; set; }
        public ProductCategory productCategory { get; set; }
    }
}

src/Web/Microservices.Web.Frontend/Microservices.Web.Frontend/Controllers/BasketController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microservices.Web.Frontend.Models.DTO;
using Microservices.Web.Frontend.Models.DTO.Basket;
using Microservices.Web.Frontend.Services.BasketServices;
using Microservices.Web.Frontend.Services.DiscountService;
using Microservices.Web.Frontend.Services.ProductServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Microservices.Web.Frontend.Controllers
{
    [Authorize]
    public class BasketController : Controller
    {
        #region constructor

        private readonly IBasketService basketService;
        private readonly IProductService productService;
        private readonly IDiscountService discountService;
        public BasketController(IBasketService basketService,
            IProductService productService,
            IDiscountService discountService)
        {
            this.basketService = basketService;
            this.productService = productService;
            this.discountService = discountService;
        }

        #endregion

        public async Task<IActionResult> Index()
        {
            var userId = HttpContext.User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value;

            var basket = await basketService.GetBasket(userId);

            if (basket != null && basket.DiscountId.HasValue)
            {
                var discount = discountService.GetDiscountById(basket.DiscountId.Value);
                basket.DiscountDetail = new DiscountInBasketDTO()
                {
                    Amount = discount.Data.Amount,
                    DiscountCode = discount.Data.Code,
                };
            }

            return View(basket);
        }

        public async Task<IActionResult> Delete(Guid Id)
        {
            var userId = HttpContext.User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value;

            await basketService.DeleteFromBasket(Id, userId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddToBasket(Guid ProductId)
        {
            var userId = HttpContext.User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value;

            var product = productService.GetProduct(ProductId);
            var basket = await basketService.GetBasket(userId);

            AddToBasketDTO item = new AddToBasketDTO()
            {
                UserId = userId,
                BasketId = basket.Id,
                ImageUrl = product.image.ToString(),
                ProductId = product.id,
                ProductName = product.name,
                Quantity = 1,
                UnitPrice = product.price,
            };
            await basketService.AddToBasket(item, userId);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(Guid BasketItemId, int quantity)
        {
            var userId = HttpContext.User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value;

            await basketService.UpdateQuantity(BasketItemId, quantity, userId);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> ApplyDiscount(string DiscountCode)
        {
            if (string.IsNullOrWhiteSpace(DiscountCode))
            {
                return Json(new ResultDTO()
                {
                    IsSuccess = false,
                    Message = "Please enter the discount code"
                });
            }
            var discount = discountService.GetDiscountByCode(DiscountCode);
            if (discount.IsSuccess == true)
            {
                if (discount.Data.Used)
                {
                    return Json(new ResultDTO
                    {
                        IsSuccess = false,
                        Message = "This discount code has already been used"
                    });
                }

                var userId = HttpContext.User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value;

                var basket = await basketService.GetBasket(userId);
                //basketService.ApplyDiscountToBasket(Guid.Parse(basket.Id), discount.Data.Id);
                await basketService.ApplyDiscountToBasket(basket.Id, discount.Data.Id, userId);
                discountService.UseDiscount(discount.Data.Id);
                return Json(new ResultDTO
                {
                    IsSuccess = true,
                    Message = "The discount code has been successfully applied to your shopping cart",
                });
            }
            else
            {
                return Json(new ResultDTO
                {
                    IsSuccess = false,
                    Message = discount.Message,
                });
            }
        }

        #region checkout

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutDTO checkout)
        {
            var userId = HttpContext.User.Claims.FirstOrDefault(p => p.Type == ClaimTypes.NameIdentifier)?.Value;

            checkout.UserId = userId;
            checkout.BasketId = basketService.GetBasket(userId).Result.Id;
            //checkout.BasketId = Guid.Parse(basketService.GetBasket(UserId).Id);
            var result = await basketService.Checkout(checkout);
            if (result.IsSuccess)
                return RedirectToAction("OrderCreated");

            // creating message
            return View(checkout);
        }

        #endregion

        public IActionResult OrderCreated()
        {
            return View();
        }
    }

}

src/Web/Microservices.Web.Frontend/Microservices.Web.Frontend/Controllers/ProductController.cs
using System;
using Microservices.Web.Frontend.Services.ProductServices;
using Microsoft.AspNetCore.Mvc;

namespace Microservices.Web.Frontend.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService productService;

        public ProductController(IProductService productService)
        {
            this.productService = productService;
        }
        public IActionResult Index()
        {
            var products = productService.GetAllProduct();
            return View(products);
        }

        public IActionResult Details(Guid id)
        {
            var product = productService.GetProduct(id);
            return View(product);
        }
    }
}

src/Web/Microservices.Web.Frontend/Microservices.Web.Frontend/Views/Product/Details.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model Microservices.Web.Frontend.Models.DTO.Product.ProductDto

@{
    ViewData["Title"] = Model.name ;
}

<h1>@Model.name</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.price)
        </dd>
    </dl>
</div>
<div>
     <a asp-action="Index">Back to List</a>
</div>

src/Web/Microservices.Web.Frontend/Microservices.Web.Frontend/Views/Product/Index.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<Microservices.Web.Frontend.Models.DTO.Product.ProductDto>

@{
    ViewData["Title"] = "Products";
}

<h1>Products </h1>

<table class="table table-hover table-bordered table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.price)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.id)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @item.price.ToString("n0")$
                    </td>
                    <td>
                        <a asp-action="Details"
                           asp-controller="Product"
                           asp-route-id="@item.id">
                            details
                        </a>
                        <a asp-action="AddToBasket" asp-controller="Basket" asp-route-ProductId="@item.id" class="btn btn-success"
                           asp-antiforgery="true" data-method="post">
                            Add To Basket
                        </a>
                    </td>
                </tr>
            }
        }
    </tbody>
</table>